name: TabCompleteFilter
main: lee.code.tcf.TabCompleteFilter
version: ${project.version}
api-version: 1.13
author: Lee

commands:
  tcf:
    description: Main command for the plugin.
    permission: tcf.command.use