name: TabCompleteFilter
main: lee.code.tcf.spigot.TabCompleteFilter
version: ${version}
api-version: 1.13
folia-supported: true
author: Lee
commands:
  tcf:
    description: Main tab complete filter command.
    permission: tcf.command.use
